language: node_js
node_js:
    - "node"
notifications:
    email: false
branches:
    only:
      - master
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - chown -R root /usr/lib/chromium-browser/chrome-sandbox
    - chmod 4755 /usr/lib/chromium-browser/chrome-sandbox

